version: '3'

services:

  web:
      build: .
      command: >
        sh -c "python manage.py collectstatic --noinput &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
      volumes:
        - .:/code
        - .db_data/db.sqlite3:/db.sqlite3
      ports:
        - "8000:8000"
