# Generated by Django 4.0.2 on 2022-02-15 21:45

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_company_established_alter_review_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to=api.models.upload_to),
        ),
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to=api.models.upload_to),
        ),
    ]
