# Generated by Django 4.0.2 on 2022-02-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_actor_img_movie_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
