# Generated by Django 4.0.2 on 2022-02-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_profile_reviewed_movies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
