# Generated by Django 4.0.2 on 2022-03-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_movie_company_alter_movie_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
    ]
